//! `/api/v1/student/flashcards` — the student's own flashcard notebook and the
//! spaced-repetition review step.
//!
//! There is deliberately **no create route here**. Cards are written by the
//! live session through `dg_db::models::flashcards::create` when a turn
//! produces one; nothing is generated by an LLM on this path, and a student
//! cannot author a card into their own graded notebook from the browser.
//!
//! Self-only: the notebook is keyed by the caller's own `students` row, and
//! every query in `dg_db::models::flashcards` binds `student_id` as a mandatory
//! predicate. Another student's card id selects no row, so "not yours" and
//! "does not exist" are the same `404` — a `403` would confirm the id exists.
//!
//! "Due" is the student's **own** calendar date (`students.timezone`), never the
//! server's: `due_on` is a `DATE`, and comparing it against a UTC today is the
//! NN-3 bug class applied to revision instead of voice.

use axum::{
    extract::{Path, Query, State},
    http::HeaderMap,
    Json,
};
use chrono::{DateTime, NaiveDate, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use dg_core::{BlockId, Capability, FlashcardId, PublicError};
use dg_db::models::flashcards;

use crate::extractors::{AuthenticatedActor, JsonBody};
use crate::state::AppState;

/// One card.
///
/// Carries no `student_id`: like the exam score card, the student-facing shape
/// has no field that could ever hold another student's identity.
#[derive(Debug, Serialize)]
pub struct FlashcardResponse {
    pub id: Uuid,
    pub block_id: Uuid,
    pub block_no: i16,
    pub block_title: String,
    pub front: String,
    pub back: String,
    pub topic: Option<String>,
    /// The live session that produced the card, when one did.
    pub source_session_id: Option<Uuid>,
    /// A calendar date in the student's own zone.
    pub due_on: NaiveDate,
    pub interval_days: i16,
    /// SM-2 ease in permille (250 = 2.50), kept integral so the schedule is
    /// exactly reproducible.
    pub ease: i16,
    /// Whether the card is due as of the student's local today — computed
    /// server-side so the client never has to compare dates across zones.
    pub is_due: bool,
    pub reviewed_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

impl FlashcardResponse {
    fn from_card(c: flashcards::Flashcard, today: NaiveDate) -> Self {
        Self {
            id: c.id.into_uuid(),
            block_id: c.block_id.into_uuid(),
            block_no: c.block_no,
            block_title: c.block_title,
            front: c.front,
            back: c.back,
            topic: c.topic,
            source_session_id: c.source_session_id.map(|s| s.into_uuid()),
            is_due: c.due_on <= today,
            due_on: c.due_on,
            interval_days: c.interval_days,
            ease: c.ease,
            reviewed_at: c.reviewed_at,
            created_at: c.created_at,
        }
    }
}

#[derive(Debug, Deserialize)]
pub struct ListFlashcardsQuery {
    /// `true` narrows the notebook to cards due on or before the student's
    /// local today. Absent or `false` returns the whole notebook.
    #[serde(default)]
    pub due_only: Option<bool>,
    #[serde(default)]
    pub block_id: Option<Uuid>,
    #[serde(default)]
    pub limit: Option<i64>,
    #[serde(default)]
    pub offset: Option<i64>,
}

pub async fn list_flashcards(
    State(state): State<AppState>,
    AuthenticatedActor(actor): AuthenticatedActor,
    Query(query): Query<ListFlashcardsQuery>,
) -> Result<(HeaderMap, Json<Vec<FlashcardResponse>>), PublicError> {
    actor.require(Capability::ViewOwnContext)?;

    let student = super::own_student(&state, &actor).await?;
    let page = crate::admin::page(query.limit, query.offset, 50)?;
    let today = quota::local_date(Utc::now(), quota::resolve_timezone(&student.timezone));

    let due_filter = if query.due_only.unwrap_or(false) {
        Some(today)
    } else {
        None
    };
    let block_id = query.block_id.map(BlockId::from);

    let total = flashcards::count_for_student(&state.pool, student.id, due_filter, block_id)
        .await
        .map_err(PublicError::from)?;
    let rows = flashcards::list_for_student(
        &state.pool,
        student.id,
        due_filter,
        block_id,
        page.limit,
        page.offset,
    )
    .await
    .map_err(PublicError::from)?;

    Ok((
        crate::admin::total_count(total),
        Json(
            rows.into_iter()
                .map(|c| FlashcardResponse::from_card(c, today))
                .collect(),
        ),
    ))
}

#[derive(Debug, Deserialize)]
pub struct ReviewFlashcardRequest {
    /// Whether the student recalled the card. The SM-2-lite step is derived
    /// from this alone — there is no client-supplied interval, ease, or due
    /// date, so a client cannot schedule its own card into the far future to
    /// clear its queue.
    pub recalled: bool,
}

/// `POST /api/v1/student/flashcards/{id}/review` — record a review and return
/// the card with its new schedule.
pub async fn review_flashcard(
    State(state): State<AppState>,
    AuthenticatedActor(actor): AuthenticatedActor,
    Path(id): Path<Uuid>,
    JsonBody(payload): JsonBody<ReviewFlashcardRequest>,
) -> Result<Json<FlashcardResponse>, PublicError> {
    actor.require(Capability::ViewOwnContext)?;

    let student = super::own_student(&state, &actor).await?;
    let today = quota::local_date(Utc::now(), quota::resolve_timezone(&student.timezone));

    // Ownership is a predicate inside the `UPDATE`, not a check on a row
    // already read: another student's card id updates nothing and comes back
    // `None`, which is the same `404` a missing id gets.
    let card = flashcards::review(
        &state.pool,
        student.id,
        FlashcardId::from(id),
        payload.recalled,
        today,
    )
    .await
    .map_err(PublicError::from)?
    .ok_or(PublicError::NotFound)?;

    Ok(Json(FlashcardResponse::from_card(card, today)))
}

#[cfg(test)]
mod tests {
    use super::*;
    use dg_core::{Actor, Role, UserId};

    #[test]
    fn a_student_may_read_and_review_its_own_notebook() {
        let actor = Actor::new(UserId::new(), Role::Student, vec![]);
        assert!(actor.require(Capability::ViewOwnContext).is_ok());
    }

    /// Neither route takes a student selector. Exhaustive destructuring so
    /// adding one would stop this compiling.
    #[test]
    fn the_flashcard_routes_cannot_name_another_student() {
        let ListFlashcardsQuery {
            due_only,
            block_id,
            limit,
            offset,
        } = ListFlashcardsQuery {
            due_only: Some(true),
            block_id: None,
            limit: None,
            offset: None,
        };
        assert_eq!(due_only, Some(true));
        assert!(block_id.is_none());
        assert!(limit.is_none() && offset.is_none());

        let ReviewFlashcardRequest { recalled } = ReviewFlashcardRequest { recalled: true };
        assert!(recalled);
    }

    #[test]
    fn a_card_carries_no_student_identity() {
        let json = serde_json::to_value(FlashcardResponse {
            id: Uuid::nil(),
            block_id: Uuid::nil(),
            block_no: 3,
            block_title: "Unit 3".into(),
            front: "What is sandhi?".into(),
            back: "Euphonic combination".into(),
            topic: Some("Phonology".into()),
            source_session_id: None,
            due_on: NaiveDate::from_ymd_opt(2026, 9, 13).expect("a real date"),
            interval_days: 6,
            ease: 260,
            is_due: true,
            reviewed_at: None,
            created_at: Utc::now(),
        })
        .expect("serialises");

        assert!(json.get("student_id").is_none());
        assert!(json.get("student_name").is_none());
    }

    /// `is_due` is computed against the student's local date, not the server's.
    #[test]
    fn a_card_is_due_when_its_date_has_arrived_in_the_students_own_calendar() {
        let today = NaiveDate::from_ymd_opt(2026, 9, 13).expect("a real date");
        let yesterday = NaiveDate::from_ymd_opt(2026, 9, 12).expect("a real date");
        let tomorrow = NaiveDate::from_ymd_opt(2026, 9, 14).expect("a real date");

        assert!(yesterday <= today, "overdue counts as due");
        assert!(today <= today, "due today counts as due");
        assert!(!(tomorrow <= today), "tomorrow is not due yet");
    }

    /// The scheduler is `crates/db`'s pure function; this pins the behaviour
    /// this route depends on — a lapse must put the card back in tomorrow's
    /// queue rather than pushing it away.
    #[test]
    fn a_lapsed_card_returns_to_the_queue_tomorrow() {
        let (interval, ease) = flashcards::schedule_next(6, 250, false);
        assert_eq!(interval, 1);
        assert!(ease < 250, "ease drops on a lapse");
    }

    #[test]
    fn a_recalled_card_spaces_out() {
        let (first, _) = flashcards::schedule_next(0, 250, true);
        assert_eq!(first, 1);
        let (second, _) = flashcards::schedule_next(1, 250, true);
        assert_eq!(second, 6);
        let (third, ease) = flashcards::schedule_next(6, 250, true);
        assert!(third > 6, "the interval grows with the ease");
        assert!(ease > 250);
    }
}
